[package]
name = "entry_point"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
closure = { version = "0.1.0", path = "../closure" }


[lints]
workspace = true
